In [32]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
import xgboost as xgb
 
iris = datasets.load_iris()
X = iris.data
Y= iris.target
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,
                                                    random_state=42)

dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)
param = {'max_depth': 3, 'eta': 0.3,'silent': 1,
         'objective': 'multi:softprob','num_class':3}
num_round = 20
bst = xgb.train(param, dtrain, num_round)
preds = bst.predict(dtest)
print (preds)

[[0.00563804 0.97755206 0.01680986]
 [0.98254657 0.01395846 0.00349498]
 [0.00363749 0.00615226 0.9902103 ]
 [0.00564738 0.97917044 0.0151822 ]
 [0.00540075 0.93640935 0.0581899 ]
 [0.98607963 0.0104128  0.00350755]
 [0.00438964 0.99041265 0.0051977 ]
 [0.0156953  0.06653062 0.917774  ]
 [0.0063378  0.94877166 0.04489058]
 [0.00438964 0.99041265 0.0051977 ]
 [0.01785045 0.07566603 0.9064835 ]
 [0.99054164 0.00561866 0.00383973]
 [0.98254657 0.01395846 0.00349498]
 [0.990855   0.00562044 0.00352453]
 [0.990855   0.00562044 0.00352453]
 [0.00435676 0.9863815  0.00926175]
 [0.0028351  0.00545694 0.991708  ]
 [0.00506935 0.98753244 0.00739827]
 [0.00435527 0.98265946 0.01298527]
 [0.00283684 0.00484793 0.9923152 ]
 [0.990855   0.00562044 0.00352453]
 [0.01177546 0.08546324 0.90276134]
 [0.990855   0.00562044 0.00352453]
 [0.00283684 0.00484793 0.9923152 ]
 [0.00561747 0.01081239 0.98357016]
 [0.00363441 0.00699543 0.9893701 ]
 [0.00363749 0.00615226 0.9902103 ]
 [0.00561747 0.01081239 0.98